# Generated by Django 3.2.8 on 2021-10-14 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='comments',
            new_name='entity_comments',
        ),
    ]
