# Generated by Django 3.2.8 on 2021-10-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_rename_comments_entity_entity_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposttag',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='entitythrough',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
