# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 12:19


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20170314_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('color', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='richtextpage',
            name='entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Entity'),
        ),
    ]
