# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 12:41


from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('cms', '0003_auto_20170524_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='color',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='name',
        ),
        migrations.RemoveField(
            model_name='richtextpage',
            name='entity',
        ),
        migrations.AddField(
            model_name='entity',
            name='content_object',
            field=modelcluster.fields.ParentalKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='entity_pages', to='cms.RichTextPage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entity',
            name='tag',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='cms_entity_items', to='taggit.Tag'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='richtextpage',
            name='entities',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='cms.Entity', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
