# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 08:44


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20170524_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='richtextpage',
            name='entities',
        ),
        migrations.DeleteModel(
            name='Entity',
        ),
    ]
