# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 15:24


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_objectindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectpage',
            name='entities',
            field=models.ManyToManyField(to='cms.Entity'),
        ),
    ]
