# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-03 09:50


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_entity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'verbose_name': 'Entity', 'verbose_name_plural': 'Entities'},
        ),
        migrations.AddField(
            model_name='entity',
            name='bibliog',
            field=models.TextField(blank=True, null=True, verbose_name='Bibliographic Details'),
        ),
        migrations.AddField(
            model_name='entity',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Comments'),
        ),
        migrations.AddField(
            model_name='entity',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entity_creator', to='cms.Entity', verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='entity',
            name='date_from',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AddField(
            model_name='entity',
            name='date_to',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='entity',
            name='location',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='entity',
            name='location_purchase',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Place of Purchase'),
        ),
        migrations.AddField(
            model_name='entity',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entity_recipient', to='cms.Entity', verbose_name='Recipient'),
        ),
        migrations.AddField(
            model_name='entity',
            name='subtype',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Subtype/Role'),
        ),
    ]
