# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-12 13:32


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_auto_20170703_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entity_creator', to='cms.Entity', verbose_name='Creator'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entity_recipient', to='cms.Entity', verbose_name='Recipient'),
        ),
    ]
