# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-25 19:07


from django.db import migrations, models
import django.db.models.deletion
import wagtail.contrib.table_block.blocks
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtaildocs.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_auto_20171212_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='date_mozart',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Date related to mozart'),
        ),
        migrations.AddField(
            model_name='entity',
            name='location_mozart',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Location Related to Mozart'),
        ),
        migrations.AddField(
            model_name='entity',
            name='mozart_relevence',
            field=models.TextField(blank=True, null=True, verbose_name='Mozart Relevence'),
        ),
        migrations.AddField(
            model_name='entity',
            name='sublocation',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Sublocation'),
        ),
        migrations.AlterField(
            model_name='blogindexpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([(b'intro', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow')), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow')), (b'pullquote', wagtail.wagtailcore.blocks.RichTextBlock(classname='pullquote', icon='openquote')), (b'table', wagtail.contrib.table_block.blocks.TableBlock()), (b'document', wagtail.wagtaildocs.blocks.DocumentChooserBlock(icon='doc-full-inverse'))]),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([(b'intro', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow')), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow')), (b'pullquote', wagtail.wagtailcore.blocks.RichTextBlock(classname='pullquote', icon='openquote')), (b'table', wagtail.contrib.table_block.blocks.TableBlock()), (b'document', wagtail.wagtaildocs.blocks.DocumentChooserBlock(icon='doc-full-inverse'))]),
        ),
        migrations.AlterField(
            model_name='entity',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([(b'intro', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow')), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow')), (b'pullquote', wagtail.wagtailcore.blocks.RichTextBlock(classname='pullquote', icon='openquote')), (b'table', wagtail.contrib.table_block.blocks.TableBlock()), (b'document', wagtail.wagtaildocs.blocks.DocumentChooserBlock(icon='doc-full-inverse'))]),
        ),
        migrations.AlterField(
            model_name='entity',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entity_creator', to='cms.Entity', verbose_name='Author/Creator'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='date_from',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='date_to',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='entitytype',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([(b'intro', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow')), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow')), (b'pullquote', wagtail.wagtailcore.blocks.RichTextBlock(classname='pullquote', icon='openquote')), (b'table', wagtail.contrib.table_block.blocks.TableBlock()), (b'document', wagtail.wagtaildocs.blocks.DocumentChooserBlock(icon='doc-full-inverse'))]),
        ),
        migrations.AlterField(
            model_name='entitytype',
            name='colour',
            field=models.CharField(help_text='You            can use the following colours:            lightgreen, darkgreen, lightpurple,            dark, purple, yellow, orange, red, lightblue,            darkblue, lightbrown, darkbrown and lightgray.', max_length=128),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([(b'intro', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow')), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow')), (b'pullquote', wagtail.wagtailcore.blocks.RichTextBlock(classname='pullquote', icon='openquote')), (b'table', wagtail.contrib.table_block.blocks.TableBlock()), (b'document', wagtail.wagtaildocs.blocks.DocumentChooserBlock(icon='doc-full-inverse'))]),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([(b'intro', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow')), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow')), (b'pullquote', wagtail.wagtailcore.blocks.RichTextBlock(classname='pullquote', icon='openquote')), (b'table', wagtail.contrib.table_block.blocks.TableBlock()), (b'document', wagtail.wagtaildocs.blocks.DocumentChooserBlock(icon='doc-full-inverse'))]),
        ),
        migrations.AlterField(
            model_name='objectindexpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([(b'intro', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow')), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow')), (b'pullquote', wagtail.wagtailcore.blocks.RichTextBlock(classname='pullquote', icon='openquote')), (b'table', wagtail.contrib.table_block.blocks.TableBlock()), (b'document', wagtail.wagtaildocs.blocks.DocumentChooserBlock(icon='doc-full-inverse'))]),
        ),
        migrations.AlterField(
            model_name='objectpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([(b'intro', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow')), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow')), (b'pullquote', wagtail.wagtailcore.blocks.RichTextBlock(classname='pullquote', icon='openquote')), (b'table', wagtail.contrib.table_block.blocks.TableBlock()), (b'document', wagtail.wagtaildocs.blocks.DocumentChooserBlock(icon='doc-full-inverse'))]),
        ),
        migrations.AlterField(
            model_name='richtextpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([(b'intro', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow')), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow')), (b'pullquote', wagtail.wagtailcore.blocks.RichTextBlock(classname='pullquote', icon='openquote')), (b'table', wagtail.contrib.table_block.blocks.TableBlock()), (b'document', wagtail.wagtaildocs.blocks.DocumentChooserBlock(icon='doc-full-inverse'))]),
        ),
    ]
