# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-25 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('cms', '0019_auto_20180325_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityThrough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='throughentity', to='cms.Entity')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='throughpage', to='wagtailcore.Page')),
            ],
        ),
        migrations.RemoveField(
            model_name='objectpage',
            name='entities',
        ),
    ]
