# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-01 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.contrib.table_block.blocks
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtaildocs.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180425_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='creator_text',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Author/Creator (Text)'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='subtype',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Category/Role'),
        ),
        migrations.AlterField(
            model_name='entitytype',
            name='colour',
            field=models.CharField(help_text='You            can use the following colours:            lightgreen, darkgreen, lightpurple,            darkpurple, yellow, orange, red, lightblue,            darkblue, lightbrown, darkbrown and lightgray.', max_length=128),
        ),
    ]
