# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-01 13:46


from django.db import migrations
import wagtail.contrib.table_block.blocks
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtaildocs.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0023_auto_20180501_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='mozart_relevence',
            field=wagtail.wagtailcore.fields.StreamField([(b'intro', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow')), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow')), (b'pull_quote', wagtail.wagtailcore.blocks.RichTextBlock(icon='openquote')), (b'table', wagtail.contrib.table_block.blocks.TableBlock()), (b'footnote', wagtail.wagtailcore.blocks.StructBlock([(b'numeral', wagtail.wagtailcore.blocks.TextBlock()), (b'reference', wagtail.wagtailcore.blocks.TextBlock())])), (b'document', wagtail.wagtaildocs.blocks.DocumentChooserBlock(icon='doc-full-inverse'))], blank=True, null=True, verbose_name='Mozart Relevence'),
        ),
    ]
