# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-01 21:11


from django.db import migrations
import wagtail.contrib.table_block.blocks
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtaildocs.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0024_auto_20180501_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogindexpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([(b'intro', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow', required=False)), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow', required=False)), (b'pull_quote', wagtail.wagtailcore.blocks.RichTextBlock(icon='openquote', required=False)), (b'table', wagtail.contrib.table_block.blocks.TableBlock(required=False)), (b'footnote', wagtail.wagtailcore.blocks.StructBlock([(b'numeral', wagtail.wagtailcore.blocks.TextBlock()), (b'reference', wagtail.wagtailcore.blocks.TextBlock())], required=False)), (b'document', wagtail.wagtaildocs.blocks.DocumentChooserBlock(icon='doc-full-inverse', required=False))]),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([(b'intro', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow', required=False)), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow', required=False)), (b'pull_quote', wagtail.wagtailcore.blocks.RichTextBlock(icon='openquote', required=False)), (b'table', wagtail.contrib.table_block.blocks.TableBlock(required=False)), (b'footnote', wagtail.wagtailcore.blocks.StructBlock([(b'numeral', wagtail.wagtailcore.blocks.TextBlock()), (b'reference', wagtail.wagtailcore.blocks.TextBlock())], required=False)), (b'document', wagtail.wagtaildocs.blocks.DocumentChooserBlock(icon='doc-full-inverse', required=False))]),
        ),
        migrations.AlterField(
            model_name='entity',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([(b'intro', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow', required=False)), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow', required=False)), (b'pull_quote', wagtail.wagtailcore.blocks.RichTextBlock(icon='openquote', required=False)), (b'table', wagtail.contrib.table_block.blocks.TableBlock(required=False)), (b'footnote', wagtail.wagtailcore.blocks.StructBlock([(b'numeral', wagtail.wagtailcore.blocks.TextBlock()), (b'reference', wagtail.wagtailcore.blocks.TextBlock())], required=False)), (b'document', wagtail.wagtaildocs.blocks.DocumentChooserBlock(icon='doc-full-inverse', required=False))], verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='mozart_relevence',
            field=wagtail.wagtailcore.fields.StreamField([(b'intro', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow', required=False)), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow', required=False)), (b'pull_quote', wagtail.wagtailcore.blocks.RichTextBlock(icon='openquote', required=False)), (b'table', wagtail.contrib.table_block.blocks.TableBlock(required=False)), (b'footnote', wagtail.wagtailcore.blocks.StructBlock([(b'numeral', wagtail.wagtailcore.blocks.TextBlock()), (b'reference', wagtail.wagtailcore.blocks.TextBlock())], required=False)), (b'document', wagtail.wagtaildocs.blocks.DocumentChooserBlock(icon='doc-full-inverse', required=False))], blank=True, null=True, verbose_name='Mozart Relevence'),
        ),
        migrations.AlterField(
            model_name='entitytype',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([(b'intro', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow', required=False)), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow', required=False)), (b'pull_quote', wagtail.wagtailcore.blocks.RichTextBlock(icon='openquote', required=False)), (b'table', wagtail.contrib.table_block.blocks.TableBlock(required=False)), (b'footnote', wagtail.wagtailcore.blocks.StructBlock([(b'numeral', wagtail.wagtailcore.blocks.TextBlock()), (b'reference', wagtail.wagtailcore.blocks.TextBlock())], required=False)), (b'document', wagtail.wagtaildocs.blocks.DocumentChooserBlock(icon='doc-full-inverse', required=False))]),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([(b'intro', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow', required=False)), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow', required=False)), (b'pull_quote', wagtail.wagtailcore.blocks.RichTextBlock(icon='openquote', required=False)), (b'table', wagtail.contrib.table_block.blocks.TableBlock(required=False)), (b'footnote', wagtail.wagtailcore.blocks.StructBlock([(b'numeral', wagtail.wagtailcore.blocks.TextBlock()), (b'reference', wagtail.wagtailcore.blocks.TextBlock())], required=False)), (b'document', wagtail.wagtaildocs.blocks.DocumentChooserBlock(icon='doc-full-inverse', required=False))]),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([(b'intro', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow', required=False)), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow', required=False)), (b'pull_quote', wagtail.wagtailcore.blocks.RichTextBlock(icon='openquote', required=False)), (b'table', wagtail.contrib.table_block.blocks.TableBlock(required=False)), (b'footnote', wagtail.wagtailcore.blocks.StructBlock([(b'numeral', wagtail.wagtailcore.blocks.TextBlock()), (b'reference', wagtail.wagtailcore.blocks.TextBlock())], required=False)), (b'document', wagtail.wagtaildocs.blocks.DocumentChooserBlock(icon='doc-full-inverse', required=False))]),
        ),
        migrations.AlterField(
            model_name='objectindexpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([(b'intro', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow', required=False)), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow', required=False)), (b'pull_quote', wagtail.wagtailcore.blocks.RichTextBlock(icon='openquote', required=False)), (b'table', wagtail.contrib.table_block.blocks.TableBlock(required=False)), (b'footnote', wagtail.wagtailcore.blocks.StructBlock([(b'numeral', wagtail.wagtailcore.blocks.TextBlock()), (b'reference', wagtail.wagtailcore.blocks.TextBlock())], required=False)), (b'document', wagtail.wagtaildocs.blocks.DocumentChooserBlock(icon='doc-full-inverse', required=False))]),
        ),
        migrations.AlterField(
            model_name='objectpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([(b'intro', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow', required=False)), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow', required=False)), (b'pull_quote', wagtail.wagtailcore.blocks.RichTextBlock(icon='openquote', required=False)), (b'table', wagtail.contrib.table_block.blocks.TableBlock(required=False)), (b'footnote', wagtail.wagtailcore.blocks.StructBlock([(b'numeral', wagtail.wagtailcore.blocks.TextBlock()), (b'reference', wagtail.wagtailcore.blocks.TextBlock())], required=False)), (b'document', wagtail.wagtaildocs.blocks.DocumentChooserBlock(icon='doc-full-inverse', required=False))]),
        ),
        migrations.AlterField(
            model_name='richtextpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([(b'intro', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow', required=False)), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow', required=False)), (b'pull_quote', wagtail.wagtailcore.blocks.RichTextBlock(icon='openquote', required=False)), (b'table', wagtail.contrib.table_block.blocks.TableBlock(required=False)), (b'footnote', wagtail.wagtailcore.blocks.StructBlock([(b'numeral', wagtail.wagtailcore.blocks.TextBlock()), (b'reference', wagtail.wagtailcore.blocks.TextBlock())], required=False)), (b'document', wagtail.wagtaildocs.blocks.DocumentChooserBlock(icon='doc-full-inverse', required=False))]),
        ),
    ]
