# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-12 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('cms', '0026_auto_20180612_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectpage',
            name='homepage_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='objectpage',
            name='homepage_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
