# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-10-19 14:00


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('cms', '0027_homepage_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='mozart_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
