# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-13 17:29
from __future__ import unicode_literals

from django.db import migrations
import wagtail.contrib.table_block.blocks
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtaildocs.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0029_auto_20190815_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogindexpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('intro', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow', required=False)), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow', required=False)), ('pull_quote', wagtail.wagtailcore.blocks.RichTextBlock(icon='openquote', required=False)), ('table', wagtail.contrib.table_block.blocks.TableBlock(required=False)), ('footnote', wagtail.wagtailcore.blocks.StructBlock((('numeral', wagtail.wagtailcore.blocks.TextBlock()), ('reference', wagtail.wagtailcore.blocks.TextBlock())), required=False)), ('document', wagtail.wagtaildocs.blocks.DocumentChooserBlock(icon='doc-full-inverse', required=False)))),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('intro', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow', required=False)), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow', required=False)), ('pull_quote', wagtail.wagtailcore.blocks.RichTextBlock(icon='openquote', required=False)), ('table', wagtail.contrib.table_block.blocks.TableBlock(required=False)), ('footnote', wagtail.wagtailcore.blocks.StructBlock((('numeral', wagtail.wagtailcore.blocks.TextBlock()), ('reference', wagtail.wagtailcore.blocks.TextBlock())), required=False)), ('document', wagtail.wagtaildocs.blocks.DocumentChooserBlock(icon='doc-full-inverse', required=False)))),
        ),
        migrations.AlterField(
            model_name='entity',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('intro', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow', required=False)), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow', required=False)), ('pull_quote', wagtail.wagtailcore.blocks.RichTextBlock(icon='openquote', required=False)), ('table', wagtail.contrib.table_block.blocks.TableBlock(required=False)), ('footnote', wagtail.wagtailcore.blocks.StructBlock((('numeral', wagtail.wagtailcore.blocks.TextBlock()), ('reference', wagtail.wagtailcore.blocks.TextBlock())), required=False)), ('document', wagtail.wagtaildocs.blocks.DocumentChooserBlock(icon='doc-full-inverse', required=False))), verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='mozart_relevence',
            field=wagtail.wagtailcore.fields.StreamField((('intro', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow', required=False)), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow', required=False)), ('pull_quote', wagtail.wagtailcore.blocks.RichTextBlock(icon='openquote', required=False)), ('table', wagtail.contrib.table_block.blocks.TableBlock(required=False)), ('footnote', wagtail.wagtailcore.blocks.StructBlock((('numeral', wagtail.wagtailcore.blocks.TextBlock()), ('reference', wagtail.wagtailcore.blocks.TextBlock())), required=False)), ('document', wagtail.wagtaildocs.blocks.DocumentChooserBlock(icon='doc-full-inverse', required=False))), blank=True, null=True, verbose_name='Mozart Relevance'),
        ),
        migrations.AlterField(
            model_name='entitytype',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('intro', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow', required=False)), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow', required=False)), ('pull_quote', wagtail.wagtailcore.blocks.RichTextBlock(icon='openquote', required=False)), ('table', wagtail.contrib.table_block.blocks.TableBlock(required=False)), ('footnote', wagtail.wagtailcore.blocks.StructBlock((('numeral', wagtail.wagtailcore.blocks.TextBlock()), ('reference', wagtail.wagtailcore.blocks.TextBlock())), required=False)), ('document', wagtail.wagtaildocs.blocks.DocumentChooserBlock(icon='doc-full-inverse', required=False)))),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('intro', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow', required=False)), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow', required=False)), ('pull_quote', wagtail.wagtailcore.blocks.RichTextBlock(icon='openquote', required=False)), ('table', wagtail.contrib.table_block.blocks.TableBlock(required=False)), ('footnote', wagtail.wagtailcore.blocks.StructBlock((('numeral', wagtail.wagtailcore.blocks.TextBlock()), ('reference', wagtail.wagtailcore.blocks.TextBlock())), required=False)), ('document', wagtail.wagtaildocs.blocks.DocumentChooserBlock(icon='doc-full-inverse', required=False)))),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('intro', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow', required=False)), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow', required=False)), ('pull_quote', wagtail.wagtailcore.blocks.RichTextBlock(icon='openquote', required=False)), ('table', wagtail.contrib.table_block.blocks.TableBlock(required=False)), ('footnote', wagtail.wagtailcore.blocks.StructBlock((('numeral', wagtail.wagtailcore.blocks.TextBlock()), ('reference', wagtail.wagtailcore.blocks.TextBlock())), required=False)), ('document', wagtail.wagtaildocs.blocks.DocumentChooserBlock(icon='doc-full-inverse', required=False)))),
        ),
        migrations.AlterField(
            model_name='objectindexpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('intro', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow', required=False)), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow', required=False)), ('pull_quote', wagtail.wagtailcore.blocks.RichTextBlock(icon='openquote', required=False)), ('table', wagtail.contrib.table_block.blocks.TableBlock(required=False)), ('footnote', wagtail.wagtailcore.blocks.StructBlock((('numeral', wagtail.wagtailcore.blocks.TextBlock()), ('reference', wagtail.wagtailcore.blocks.TextBlock())), required=False)), ('document', wagtail.wagtaildocs.blocks.DocumentChooserBlock(icon='doc-full-inverse', required=False)))),
        ),
        migrations.AlterField(
            model_name='objectpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('intro', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow', required=False)), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow', required=False)), ('pull_quote', wagtail.wagtailcore.blocks.RichTextBlock(icon='openquote', required=False)), ('table', wagtail.contrib.table_block.blocks.TableBlock(required=False)), ('footnote', wagtail.wagtailcore.blocks.StructBlock((('numeral', wagtail.wagtailcore.blocks.TextBlock()), ('reference', wagtail.wagtailcore.blocks.TextBlock())), required=False)), ('document', wagtail.wagtaildocs.blocks.DocumentChooserBlock(icon='doc-full-inverse', required=False)))),
        ),
        migrations.AlterField(
            model_name='richtextpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('intro', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow', required=False)), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow', required=False)), ('pull_quote', wagtail.wagtailcore.blocks.RichTextBlock(icon='openquote', required=False)), ('table', wagtail.contrib.table_block.blocks.TableBlock(required=False)), ('footnote', wagtail.wagtailcore.blocks.StructBlock((('numeral', wagtail.wagtailcore.blocks.TextBlock()), ('reference', wagtail.wagtailcore.blocks.TextBlock())), required=False)), ('document', wagtail.wagtaildocs.blocks.DocumentChooserBlock(icon='doc-full-inverse', required=False)))),
        ),
    ]
